version: '3.9'

services:
  auth_database:
    container_name: auth_database
    build: .
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: auth_cache
    volumes:
      - redis:/var/lib/redis/data
    command: redis-server --requirepass \${REDIS_PASSWORD} --appendonly yes
    ports:
      - "16379:6379"

volumes:
  postgres:
  redis: